version: '3'

# volumes:
#   postgres_data:
#     driver: local

services:
  # db:
  #   image: postgres:latest
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=senha
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   network_mode: bridge
  #   restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=prod
    restart: always
    network_mode: bridge
    # depends_on:
    #   - db

